name: Build Android Debug APK

on:
  # Puoi avviarlo manualmente dal tab "Actions"
  workflow_dispatch:

permissions: read-all

jobs:
  build-android-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
        id: extract_branch
        
      # 1️⃣ Checkout del codice sorgente
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          
      - name: Copy files to build directory
        run: |
          mkdir -p /tmp/build
          cp -R . /tmp/build

      - name: Set FLUTTER_ROOT environment variable and build dir
        run: echo "FLUTTER_ROOT=/tmp/build/flutter/bin" >> $GITHUB_ENV
        



      - run: $FLUTTER_ROOT/flutter doctor -v

      # 3️⃣ Ottieni i pacchetti e genera codice (se serve)
      - name: Get dependencies
        run: $FLUTTER_ROOT/flutter pub get
        
      - name: Get packages and run codegen
        run: |
          bash /tmp/build/scripts/install_dependencies_with_submodule.sh
          bash /tmp/build/scripts/update_changelogs.sh

      # 4️⃣ Compila la build debug
      - name: Build debug APK
        run: |
          cd /tmp/build/android 
          $FLUTTER_ROOT/flutter build apk --debug

      # 5️⃣ Carica l’APK come artifact scaricabile
      - name: Upload debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: /tmp/build/android/build/app/outputs/flutter-apk/app-debug.apk
